CREATE TABLE "C##BDD4_26"."ABSENCE" 
   (	"IDABSENCE" NUMBER(8,0) NOT NULL ENABLE, 
	"TYPEABSENCE" VARCHAR2(20 BYTE), 
	"DATEABSENCE" DATE, 
	"NBRHEUREABSENCE" NUMBER(3,0), 
	"QUOTAABSENCE" NUMBER(3,0), 
	"IDETUDIANT" NUMBER(8,0), 
	"IDSEANCE" NUMBER(8,0), 
	"IDJUSTIFICATIF" NUMBER(8,0), 
	 CONSTRAINT "ABSENCE_PK" PRIMARY KEY ("IDABSENCE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "IDETUDIANT_ETUDIANT_IDETUDIANT" FOREIGN KEY ("IDETUDIANT")
	  REFERENCES "C##BDD4_26"."ETUDIANT" ("IDETUDIANT") ENABLE, 
	 CONSTRAINT "FK_IDJUSTIFICATIF_JUSTIFICATIF_IDJUSTIFICATIF" FOREIGN KEY ("IDJUSTIFICATIF")
	  REFERENCES "C##BDD4_26"."JUSTIFICATIF" ("IDJUSTIFICATIF") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
  
  CREATE TABLE "C##BDD4_26"."ETUDIANT" 
   (	"IDETUDIANT" NUMBER(8,0) NOT NULL ENABLE, 
	"MOTDEPASSEETUDIANT" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"NOMETUDIANT" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"PRENOMETUDIANT" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"ADRESSEMAIL" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "ETUDIANT_PK" PRIMARY KEY ("IDETUDIANT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "UN_ADRESSE" UNIQUE ("ADRESSEMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
  
   CREATE TABLE "C##BDD4_26"."GROUPE" 
   (	"NUMEROGROUPE" NUMBER(8,0) NOT NULL ENABLE, 
	"CAPACITEMAX" NUMBER(2,0) DEFAULT 35, 
	 CONSTRAINT "GROUPE_PK" PRIMARY KEY ("NUMEROGROUPE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
  
  CREATE TABLE "C##BDD4_26"."JUSTIFICATIF" 
   (	"IDJUSTIFICATIF" NUMBER(8,0) NOT NULL ENABLE, 
	"NOMJUSTIFICATIF" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"DATE_HEURE_JUSTIFICATIF" DATE DEFAULT SYSDATE, 
	"IDETUDIANT" NUMBER(8,0), 
	 CONSTRAINT "JUSTIFICATIF_PK" PRIMARY KEY ("IDJUSTIFICATIF")
  USING INDEX (CREATE UNIQUE INDEX "C##BDD4_26"."JUSTIFICATIF_PK1" ON "C##BDD4_26"."JUSTIFICATIF" ("IDJUSTIFICATIF") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" )  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
  
  CREATE TABLE "C##BDD4_26"."MATIERE" 
   (	"IDMATIERE" NUMBER(8,0) NOT NULL ENABLE, 
	"NOMMATIERE" VARCHAR2(20 BYTE), 
	"MASSEHORAIRE" NUMBER(5,0), 
	"REPARTITIONHORAIRECM" NUMBER(3,0), 
	"REPARTITIONHORAIRETD" NUMBER(3,0), 
	"REPARTITIONHORAIRETP" NUMBER(3,0), 
	"IDETUDIANT" NUMBER(8,0), 
	 CONSTRAINT "MATIERE_PK" PRIMARY KEY ("IDMATIERE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "UN_NOMMATIERE" UNIQUE ("NOMMATIERE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
  
  CREATE TABLE "C##BDD4_26"."NOTE" 
   (	"IDNOTE" NUMBER(8,0) NOT NULL ENABLE, 
	"NOMEXAMEN" VARCHAR2(20 BYTE), 
	"DATEPUBLICATION" DATE DEFAULT SYSDATE, 
	"IDETUDIANT" NUMBER(8,0), 
	"IDMATIERE" NUMBER(8,0), 
	 CONSTRAINT "NOTE_PK" PRIMARY KEY ("IDNOTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FK_IDETUDIANT_ETUDIANT_IDETUDIANT" FOREIGN KEY ("IDNOTE")
	  REFERENCES "C##BDD4_26"."ETUDIANT" ("IDETUDIANT") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
  
  CREATE TABLE "C##BDD4_26"."PROFESSEUR" 
   (	"IDPROFESSEUR" NUMBER(8,0) NOT NULL ENABLE, 
	"MOTDEPASSEPROF" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"NOMPROFESSEUR" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"PRENOMPROFESSEUR" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"NUMEROTELPROF" NUMBER(20,0), 
	"DEPARTEMENT" VARCHAR2(20 BYTE), 
	 CONSTRAINT "PROFESSEUR_PK" PRIMARY KEY ("IDPROFESSEUR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
  
  CREATE TABLE "C##BDD4_26"."SALLE" 
   (	"IDSALLE" NUMBER(8,0) NOT NULL ENABLE, 
	"NOMSALLE" VARCHAR2(20 BYTE), 
	 CONSTRAINT "SALLE_PK" PRIMARY KEY ("IDSALLE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
  
   CREATE TABLE "C##BDD4_26"."SEANCE" 
   (	"IDSEANCE" NUMBER(8,0) NOT NULL DISABLE, 
	"NOMSEANCE" VARCHAR2(20 BYTE) NOT NULL DISABLE, 
	"TYPESEANCE" VARCHAR2(20 BYTE), 
	"DATESEANCE" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"DUREESEANCE" NUMBER(3,0), 
	"IDPROFESSEUR" NUMBER(8,0), 
	"IDSALLE" NUMBER(8,0), 
	"IDMATIERE" NUMBER(8,0), 
	"NUMEROGROUPE" NUMBER(8,0), 
	 CONSTRAINT "SEANCE_PK" PRIMARY KEY ("IDSEANCE") DISABLE, 
	 CONSTRAINT "FK_IDPROFESSEUR_PROFESSEUR_IDPROFESSEUR" FOREIGN KEY ("IDPROFESSEUR")
	  REFERENCES "C##BDD4_26"."PROFESSEUR" ("IDPROFESSEUR") ENABLE, 
	 CONSTRAINT "FK_IDSALLE_SALLE_IDSALLE" FOREIGN KEY ("IDSALLE")
	  REFERENCES "C##BDD4_26"."SALLE" ("IDSALLE") ENABLE, 
	 CONSTRAINT "FK_IDMATIERE_MATIERE_MATIERE" FOREIGN KEY ("IDMATIERE")
	  REFERENCES "C##BDD4_26"."MATIERE" ("IDMATIERE") ENABLE, 
	 CONSTRAINT "FK_NUMEROGROUPE_GROUPE_NUMEROGROUPE" FOREIGN KEY ("NUMEROGROUPE")
	  REFERENCES "C##BDD4_26"."GROUPE" ("NUMEROGROUPE") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;